//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.239
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueryExPlus.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MaximizeMainWindow {
            get {
                return ((bool)(this["MaximizeMainWindow"]));
            }
            set {
                this["MaximizeMainWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsFirstRun {
            get {
                return ((bool)(this["IsFirstRun"]));
            }
            set {
                this["IsFirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ArrayList MRUFiles {
            get {
                return ((global::System.Collections.ArrayList)(this["MRUFiles"]));
            }
            set {
                this["MRUFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SQLAuthenticationDefault {
            get {
                return ((bool)(this["SQLAuthenticationDefault"]));
            }
            set {
                this["SQLAuthenticationDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ResultInGridDefault {
            get {
                return ((bool)(this["ResultInGridDefault"]));
            }
            set {
                this["ResultInGridDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public string Delimiter {
            get {
                return ((string)(this["Delimiter"]));
            }
            set {
                this["Delimiter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"")]
        public char TextDelimiter {
            get {
                return ((char)(this["TextDelimiter"]));
            }
            set {
                this["TextDelimiter"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ABORT\r\nABS\r\nABSOLUTE\r\nACCESS\r\nACTION\r\nADA\r\nADD\r\nADMIN\r\nAFTER\r\nAGGREGATE\r\nALIAS\r\nA" +
            "LL\r\nALLOCATE\r\nALTER\r\nANALYSE\r\nANALYZE\r\nAND\r\nANY\r\nARE\r\nARRAY\r\nAS\r\nASC\r\nASENSITIVE" +
            "\r\nASSERTION\r\nASSIGNMENT\r\nASYMMETRIC\r\nAT\r\nATOMIC\r\nAUTHORIZATION\r\nAVG\r\nBACKWARD\r\nB" +
            "EFORE\r\nBEGIN\r\nBETWEEN\r\nBIGINT\r\nBINARY\r\nBIT\r\nBITVAR\r\nBIT_LENGTH\r\nBLOB\r\nBOOLEAN\r\nB" +
            "OTH\r\nBREADTH\r\nBY\r\nC\r\nCACHE\r\nCALL\r\nCALLED\r\nCARDINALITY\r\nCASCADE\r\nCASCADED\r\nCASE\r\n" +
            "CAST\r\nCATALOG\r\nCATALOG_NAME\r\nCHAIN\r\nCHAR\r\nCHARACTER\r\nCHARACTERISTICS\r\nCHARACTER_" +
            "LENGTH\r\nCHARACTER_SET_CATALOG\r\nCHARACTER_SET_NAME\r\nCHARACTER_SET_SCHEMA\r\nCHAR_LE" +
            "NGTH\r\nCHECK\r\nCHECKED\r\nCHECKPOINT\r\nCLASS\r\nCLASS_ORIGIN\r\nCLOB\r\nCLOSE\r\nCLUSTER\r\nCOA" +
            "LESCE\r\nCOBOL\r\nCOLLATE\r\nCOLLATION\r\nCOLLATION_CATALOG\r\nCOLLATION_NAME\r\nCOLLATION_S" +
            "CHEMA\r\nCOLUMN\r\nCOLUMN_NAME\r\nCOMMAND_FUNCTION\r\nCOMMAND_FUNCTION_CODE\r\nCOMMENT\r\nCO" +
            "MMIT\r\nCOMMITTED\r\nCOMPLETION\r\nCONDITION_NUMBER\r\nCONNECT\r\nCONNECTION\r\nCONNECTION_N" +
            "AME\r\nCONSTRAINT\r\nCONSTRAINTS\r\nCONSTRAINT_CATALOG\r\nCONSTRAINT_NAME\r\nCONSTRAINT_SC" +
            "HEMA\r\nCONSTRUCTOR\r\nCONTAINS\r\nCONTINUE\r\nCONVERSION\r\nCONVERT\r\nCOPY\r\nCORRESPONDING\r" +
            "\nCOUNT\r\nCREATE\r\nCREATEDB\r\nCREATEUSER\r\nCROSS\r\nCUBE\r\nCURRENT\r\nCURRENT_DATE\r\nCURREN" +
            "T_PATH\r\nCURRENT_ROLE\r\nCURRENT_TIME\r\nCURRENT_TIMESTAMP\r\nCURRENT_USER\r\nCURSOR\r\nCUR" +
            "SOR_NAME\r\nCYCLE\r\nDATA\r\nDATABASE\r\nDATE\r\nDATETIME_INTERVAL_CODE\r\nDATETIME_INTERVAL" +
            "_PRECISION\r\nDAY\r\nDEALLOCATE\r\nDEC\r\nDECIMAL\r\nDECLARE\r\nDEFAULT\r\nDEFERRABLE\r\nDEFERRE" +
            "D\r\nDEFINED\r\nDEFINER\r\nDELETE\r\nDELIMITER\r\nDELIMITERS\r\nDEPTH\r\nDEREF\r\nDESC\r\nDESCRIBE" +
            "\r\nDESCRIPTOR\r\nDESTROY\r\nDESTRUCTOR\r\nDETERMINISTIC\r\nDIAGNOSTICS\r\nDICTIONARY\r\nDISCO" +
            "NNECT\r\nDISPATCH\r\nDISTINCT\r\nDO\r\nDOMAIN\r\nDOUBLE\r\nDROP\r\nDYNAMIC\r\nDYNAMIC_FUNCTION\r\n" +
            "DYNAMIC_FUNCTION_CODE\r\nEACH\r\nELSE\r\nENCODING\r\nENCRYPTED\r\nEND\r\nEND-EXEC\r\nEQUALS\r\nE" +
            "SCAPE\r\nEVERY\r\nEXCEPT\r\nEXCEPTION\r\nEXCLUSIVE\r\nEXEC\r\nEXECUTE\r\nEXISTING\r\nEXISTS\r\nEXP" +
            "LAIN\r\nEXTERNAL\r\nEXTRACT\r\nFALSE\r\nFETCH\r\nFINAL\r\nFIRST\r\nFLOAT\r\nFOR\r\nFORCE\r\nFOREIGN\r" +
            "\nFORTRAN\r\nFORWARD\r\nFOUND\r\nFREE\r\nFREEZE\r\nFROM\r\nFULL\r\nFUNCTION\r\nG\r\nGENERAL\r\nGENERA" +
            "TED\r\nGET\r\nGLOBAL\r\nGO\r\nGOTO\r\nGRANT\r\nGRANTED\r\nGROUP\r\nGROUPING\r\nHANDLER\r\nHAVING\r\nHI" +
            "ERARCHY\r\nHOLD\r\nHOST\r\nHOUR\r\nIDENTITY\r\nIGNORE\r\nILIKE\r\nIMMEDIATE\r\nIMMUTABLE\r\nIMPLEM" +
            "ENTATION\r\nIMPLICIT\r\nIN\r\nINCREMENT\r\nINDEX\r\nINDICATOR\r\nINFIX\r\nINHERITS\r\nINITIALIZE" +
            "\r\nINITIALLY\r\nINNER\r\nINOUT\r\nINPUT\r\nINSENSITIVE\r\nINSERT\r\nINSTANCE\r\nINSTANTIABLE\r\nI" +
            "NSTEAD\r\nINT\r\nINTEGER\r\nINTERSECT\r\nINTERVAL\r\nINTO\r\nINVOKER\r\nIS\r\nISNULL\r\nISOLATION\r" +
            "\nITERATE\r\nJOIN\r\nK\r\nKEY\r\nKEY_MEMBER\r\nKEY_TYPE\r\nLANCOMPILER\r\nLANGUAGE\r\nLARGE\r\nLAST" +
            "\r\nLATERAL\r\nLEADING\r\nLEFT\r\nLENGTH\r\nLESS\r\nLEVEL\r\nLIKE\r\nLIMIT\r\nLISTEN\r\nLOAD\r\nLOCAL\r" +
            "\nLOCALTIME\r\nLOCALTIMESTAMP\r\nLOCATION\r\nLOCATOR\r\nLOCK\r\nLOWER\r\nM\r\nMAP\r\nMATCH\r\nMAX\r\n" +
            "MAXVALUE\r\nMESSAGE_LENGTH\r\nMESSAGE_OCTET_LENGTH\r\nMESSAGE_TEXT\r\nMETHOD\r\nMIN\r\nMINUT" +
            "E\r\nMINVALUE\r\nMOD\r\nMODE\r\nMODIFIES\r\nMODIFY\r\nMODULE\r\nMONTH\r\nMORE\r\nMOVE\r\nMUMPS\r\nNAME" +
            "\r\nNAMES\r\nNATIONAL\r\nNATURAL\r\nNCHAR\r\nNCLOB\r\nNEW\r\nNEXT\r\nNO\r\nNOCREATEDB\r\nNOCREATEUSE" +
            "R\r\nNONE\r\nNOT\r\nNOTHING\r\nNOTIFY\r\nNOTNULL\r\nNULL\r\nNULLABLE\r\nNULLIF\r\nNUMBER\r\nNUMERIC\r" +
            "\nOBJECT\r\nOCTET_LENGTH\r\nOF\r\nOFF\r\nOFFSET\r\nOIDS\r\nOLD\r\nON\r\nONLY\r\nOPEN\r\nOPERATION\r\nOP" +
            "ERATOR\r\nOPTION\r\nOPTIONS\r\nOR\r\nORDER\r\nORDINALITY\r\nOUT\r\nOUTER\r\nOUTPUT\r\nOVERLAPS\r\nOV" +
            "ERLAY\r\nOVERRIDING\r\nOWNER\r\nPAD\r\nPARAMETER\r\nPARAMETERS\r\nPARAMETER_MODE\r\nPARAMETER_" +
            "NAME\r\nPARAMETER_ORDINAL_POSITION\r\nPARAMETER_SPECIFIC_CATALOG\r\nPARAMETER_SPECIFIC" +
            "_NAME\r\nPARAMETER_SPECIFIC_SCHEMA\r\nPARTIAL\r\nPASCAL\r\nPASSWORD\r\nPATH\r\nPENDANT\r\nPLAC" +
            "ING\r\nPLI\r\nPOSITION\r\nPOSTFIX\r\nPRECISION\r\nPREFIX\r\nPREORDER\r\nPREPARE\r\nPRESERVE\r\nPRI" +
            "MARY\r\nPRIOR\r\nPRIVILEGES\r\nPROCEDURAL\r\nPROCEDURE\r\nPUBLIC\r\nREAD\r\nREADS\r\nREAL\r\nRECHE" +
            "CK\r\nRECURSIVE\r\nREF\r\nREFERENCES\r\nREFERENCING\r\nREINDEX\r\nRELATIVE\r\nRENAME\r\nREPEATAB" +
            "LE\r\nREPLACE\r\nRESET\r\nRESTRICT\r\nRESULT\r\nRETURN\r\nRETURNED_LENGTH\r\nRETURNED_OCTET_LE" +
            "NGTH\r\nRETURNED_SQLSTATE\r\nRETURNS\r\nREVOKE\r\nRIGHT\r\nROLE\r\nROLLBACK\r\nROLLUP\r\nROUTINE" +
            "\r\nROUTINE_CATALOG\r\nROUTINE_NAME\r\nROUTINE_SCHEMA\r\nROW\r\nROWS\r\nROW_COUNT\r\nRULE\r\nSAV" +
            "EPOINT\r\nSCALE\r\nSCHEMA\r\nSCHEMA_NAME\r\nSCOPE\r\nSCROLL\r\nSEARCH\r\nSECOND\r\nSECTION\r\nSECU" +
            "RITY\r\nSELECT\r\nSELF\r\nSENSITIVE\r\nSEQUENCE\r\nSERIALIZABLE\r\nSERVER_NAME\r\nSESSION\r\nSES" +
            "SION_USER\r\nSET\r\nSETOF\r\nSETS\r\nSHARE\r\nSHOW\r\nSIMILAR\r\nSIMPLE\r\nSIZE\r\nSMALLINT\r\nSOME\r" +
            "\nSOURCE\r\nSPACE\r\nSPECIFIC\r\nSPECIFICTYPE\r\nSPECIFIC_NAME\r\nSQL\r\nSQLCODE\r\nSQLERROR\r\nS" +
            "QLEXCEPTION\r\nSQLSTATE\r\nSQLWARNING\r\nSTABLE\r\nSTART\r\nSTATE\r\nSTATEMENT\r\nSTATIC\r\nSTAT" +
            "ISTICS\r\nSTDIN\r\nSTDOUT\r\nSTORAGE\r\nSTRICT\r\nSTRUCTURE\r\nSTYLE\r\nSUBCLASS_ORIGIN\r\nSUBLI" +
            "ST\r\nSUBSTRING\r\nSUM\r\nSYMMETRIC\r\nSYSID\r\nSYSTEM\r\nSYSTEM_USER\r\nTABLE\r\nTABLE_NAME\r\nTE" +
            "MP\r\nTEMPLATE\r\nTEMPORARY\r\nTERMINATE\r\nTHAN\r\nTHEN\r\nTIME\r\nTIMESTAMP\r\nTIMEZONE_HOUR\r\n" +
            "TIMEZONE_MINUTE\r\nTO\r\nTOAST\r\nTRAILING\r\nTRANSACTION\r\nTRANSACTIONS_COMMITTED\r\nTRANS" +
            "ACTIONS_ROLLED_BACK\r\nTRANSACTION_ACTIVE\r\nTRANSFORM\r\nTRANSFORMS\r\nTRANSLATE\r\nTRANS" +
            "LATION\r\nTREAT\r\nTRIGGER\r\nTRIGGER_CATALOG\r\nTRIGGER_NAME\r\nTRIGGER_SCHEMA\r\nTRIM\r\nTRU" +
            "E\r\nTRUNCATE\r\nTRUSTED\r\nTYPE\r\nUNCOMMITTED\r\nUNDER\r\nUNENCRYPTED\r\nUNION\r\nUNIQUE\r\nUNKN" +
            "OWN\r\nUNLISTEN\r\nUNNAMED\r\nUNNEST\r\nUNTIL\r\nUPDATE\r\nUPPER\r\nUSAGE\r\nUSER\r\nUSER_DEFINED_" +
            "TYPE_CATALOG\r\nUSER_DEFINED_TYPE_NAME\r\nUSER_DEFINED_TYPE_SCHEMA\r\nUSING\r\nVACUUM\r\nV" +
            "ALID\r\nVALIDATOR\r\nVALUE\r\nVALUES\r\nVARCHAR\r\nVARIABLE\r\nVARYING\r\nVERBOSE\r\nVERSION\r\nVI" +
            "EW\r\nVOLATILE\r\nWHEN\r\nWHENEVER\r\nWHERE\r\nWITH\r\nWITHOUT\r\nWORK\r\nWRITE\r\nYEAR\r\nZONE")]
        public string SQLKeyWords {
            get {
                return ((string)(this["SQLKeyWords"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SyntaxHighlighting {
            get {
                return ((bool)(this["SyntaxHighlighting"]));
            }
            set {
                this["SyntaxHighlighting"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("|+-*/()[]{}<>=")]
        public string SQLOperators {
            get {
                return ((string)(this["SQLOperators"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkRed")]
        public global::System.Drawing.Color ColorStrings {
            get {
                return ((global::System.Drawing.Color)(this["ColorStrings"]));
            }
            set {
                this["ColorStrings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ColorKeywords {
            get {
                return ((global::System.Drawing.Color)(this["ColorKeywords"]));
            }
            set {
                this["ColorKeywords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color ColorOperators {
            get {
                return ((global::System.Drawing.Color)(this["ColorOperators"]));
            }
            set {
                this["ColorOperators"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color ColorNumbers {
            get {
                return ((global::System.Drawing.Color)(this["ColorNumbers"]));
            }
            set {
                this["ColorNumbers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastExportPath {
            get {
                return ((string)(this["LastExportPath"]));
            }
            set {
                this["LastExportPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastImportPath {
            get {
                return ((string)(this["LastImportPath"]));
            }
            set {
                this["LastImportPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowNulls {
            get {
                return ((bool)(this["ShowNulls"]));
            }
            set {
                this["ShowNulls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExpandRowNumber {
            get {
                return ((bool)(this["ExpandRowNumber"]));
            }
            set {
                this["ExpandRowNumber"] = value;
            }
        }
    }
}
